azure-pipeline.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -65,23 +65,31 @@ steps:
 
 - task: Bash@3
   displayName: 'Upload to Dropbox'
-  env:
-    DROPBOX_APP_KEY: $(dropbox_app_key)
-    DROPBOX_APP_SECRET: $(dropbox_app_secret)
-    DROPBOX_REFRESH_TOKEN: $(dropbox_refresh_token)
   inputs:
     targetType: 'inline'
     script: |
       set -e
+      
+      SETTINGS_FILE="$(Build.SourcesDirectory)/settings.properties"
+      
+      echo "Extracting credentials from settings.properties..."
+      APP_KEY=$(grep 'dropbox_app_key=' $SETTINGS_FILE | cut -d'=' -f2 | tr -d '\r')
+      APP_SECRET=$(grep 'dropbox_app_secret=' $SETTINGS_FILE | cut -d'=' -f2 | tr -d '\r')
+      REFRESH_TOKEN=$(grep 'dropbox_refresh_token=' $SETTINGS_FILE | cut -d'=' -f2 | tr -d '\r')
+
+      if [ -z "$APP_KEY" ] || [ -z "$APP_SECRET" ] || [ -z "$REFRESH_TOKEN" ]; then
+        echo "Error: One or more Dropbox credentials missing in settings.properties"
+        exit 1
+      fi
+
       echo "Refreshing Dropbox access token..."
       
-      # Fetching access token using refresh token
       RESPONSE=$(curl -s -X POST https://api.dropbox.com/oauth2/token \
-        -u "$DROPBOX_APP_KEY:$DROPBOX_APP_SECRET" \
         -d grant_type=refresh_token \
-        -d refresh_token="$DROPBOX_REFRESH_TOKEN")
+        -d refresh_token="$REFRESH_TOKEN" \
+        -d client_id="$APP_KEY" \
+        -d client_secret="$APP_SECRET")
       
-      # Extracting access_token from JSON response
       ACCESS_TOKEN=$(echo $RESPONSE | sed -n 's/.*"access_token": *"\([^"]*\)".*/\1/p')
       
       if [ -z "$ACCESS_TOKEN" ]; then
